/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/components/common/Setting/About.vue')['default']
    Advanced: typeof import('./src/components/common/Setting/Advanced.vue')['default']
    Button: typeof import('./src/components/common/HoverButton/Button.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    General: typeof import('./src/components/common/Setting/General.vue')['default']
    GithubSite: typeof import('./src/components/custom/GithubSite.vue')['default']
    HoverButton: typeof import('./src/components/common/HoverButton/index.vue')['default']
    NaiveProvider: typeof import('./src/components/common/NaiveProvider/index.vue')['default']
    PromptStore: typeof import('./src/components/common/PromptStore/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/components/common/Setting/index.vue')['default']
    SvgIcon: typeof import('./src/components/common/SvgIcon/index.vue')['default']
    UserAvatar: typeof import('./src/components/common/UserAvatar/index.vue')['default']
  }
}
